font_family JetBrainsMono Nerd Font
bold_font Victor Mono Bold
italic_font Victor Mono Medium Italic
bold_italic_font Victor Mono Bold Italic

font_size 15

cursor_shape beam
cursor_blink_interval 0

allow_remote_control             yes

adjust_line_height 110%
modify_font strikethrough_position 12px

modify_font underline_position 3
modify_font underline_thickness 150%

symbol_map U+f101-U+f27d nonicons

font_size_delta                  1
mouse_hide_wait                  1.0
close_on_child_death             yes
background_opacity               1

# window_padding_width 12
draw_minimal_borders yes
inactive_text_alpha 0.7

dynamic_background_opacity no
hide_window_decorations titlebar-only
background_opacity 0.9
background_blur 25

scrollback_lines 200000
enable_audio_bell no

kitty_mod cmd

# Permite acesso ao clipboard

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

open_url_modifiers cmd

enabled_layouts Splits,Stack

map ctrl+shift+r load_config_file
map ctrl+shift+t                 input_unicode_character
map ctrl+shift+u                 scroll_page_up
map ctrl+shift+e                 scroll_page_up
map ctrl+shift+d                 scroll_page_down
map ctrl+shift+0                 restore_font_size
map ctrl+shift+l>u>o             run_kitten text hints --type url
map ctrl+shift+l>u>c             run_kitten text hints --type url --program @
map ctrl+shift+l>u>t             run_kitten text hints --type url --program -
map ctrl+shift+l>p>c             run_kitten text hints --type regex --regex '\S*/\S+' --program @
map ctrl+shift+l>p>t             run_kitten text hints --type regex --regex '\S*/\S+' --program -
map ctrl+shift+l>w>c             run_kitten text hints --type word --program @
map ctrl+shift+l>w>t             run_kitten text hints --type word --program -
map ctrl+shift+l>l>c             run_kitten text hints --type line --program @
map ctrl+shift+l>l>t             run_kitten text hints --type line --program -

include current-theme.conf

# vim:ft=conf
