# Set day screen brightness
# 1=least bright, 99=most bright
# Example: BRIGHTNESS_DAY=37
# Default: BRIGHTNESS_DAY=
BRIGHTNESS_DAY=


# Set day screen contrast
# 1=most contrast, 99=least contrast
# Example: CONTRAST_DAY=71
# Default: CONTRAST_DAY=
CONTRAST_DAY=
