# Set night screen brightness
# 1=least bright, 99=most bright
# Example: BRIGHTNESS_NIGHT=37
# Default: BRIGHTNESS_NIGHT=
BRIGHTNESS_NIGHT=


# Set night screen colour temperature
# 1000=most red, 10000=least red
# Example: COLOUR_TEMPERATURE=4500
# Default: COLOUR_TEMPERATURE=
COLOUR_TEMPERATURE=
