#!/bin/bash

redshift -c ~/.config/redshift.conf -l manual &

bluetoothd &

xrandr --output eDP-1 --brightness 0.7 &
xrandr --output HDMI-1 --brightness 0.8 2>/dev/null &

if xsetwacom list devices | grep -q "Wacom One"; then
  xsetwacom --set "Wacom One by Wacom S Pen stylus" rotate half &
fi

xinput set-prop 12 "libinput Accel Profile Enabled" 0, 1 &
#setxkbmap -layout "br,cn,gr" -option "grp:alt_shift_toggle" &

#polybar &

anki & 

#if [ -f ~/.cache/wal/wal ]; then
#    cwp "$(cat ~/.cache/wal/wal)"
#else
#    cwp
#fi &

# conky &
# [ -x "$HOME/abrir_pdfs.sh" ] && "$HOME/abrir_pdfs.sh"