;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

include-file = ~/.config/polybar/arrows

[color]

; vim:ft=dosini

[colors]
background      = #1a1b26
background-alt  = #24283b
foreground      = #a9b1d6
primary         = #7aa2f7
secondary       = #9ece6a
alert           = #f7768e
disabled        = #565f89

black = ${xrdb:background}
white = ${xrdb:foreground}
grey = ${xrdb:color8}
red = ${xrdb:color9}
lightred = ${xrdb:color1}
purple = ${xrdb:color13}
light-purple = ${xrdb:color5}
blue = ${xrdb:color12}
light-blue = ${xrdb:color4}
cyan = ${xrdb:color14}
teal = ${xrdb:color6}
green = ${xrdb:color10}
light-green = ${xrdb:color2}
yellow = ${xrdb:color3}
orange = ${xrdb:color11}

[bar/kaay]
font-0 = 0xProto Nerd Font Mono:size=11;2
font-1 = 0xProto Nerd Font Mono:size=15;2
font-2 = 0xProto Nerd Font Mono:style=Bold:size=15;2
font-3 = 0xProto Nerd Font Mono:style=Bold:size=18;2
width = 100%
height = 20pt
radius = 8

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 3pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator =  
separator-foreground = ${colors.disabled}


modules-left = xworkspaces xwindow
modules-right = left3 xkeyboard right2 memory cpu right1 date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; tray-position = right

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:40:...%

[module/filesystem]
type = internal/fs
interval = 25

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
label-layout = %layout%

label-indicator-padding = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "󰍛 "
format-prefix-font = 2
format-prefix-foreground = ${colors.primary}
label = %percentage_used%%
label-background = ${color.yellow}

[module/cpu]
type = internal/cpu
interval = 2

format-prefix = " "
format-prefix-font = 2
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[module/temperature]
type = internal/temperature

; forma mais confiável
hwmon-path = /sys/class/hwmon/hwmon0/temp1_input
base-temperature = 20
warn-temperature = 70

interval = 2

format-prefix = " "
format-prefix-font = 3
format-prefix-foreground = ${colors.primary}

label = "%temperature-c%°C"
label-font = 0
label-warn = "%temperature-c%°C"
label-warn-foreground = ${colors.red}
label-warn-font = 0

[module/date]
type = internal/date
interval = 1

date = "%d/%m  %H:%M:%S"

format-prefix = " "
format-prefix-font = 2
format-prefix-foreground = ${colors.primary}

label = %date%

[settings]
screenchange-reload = true
pseudo-transparency = true


; vim:ft=dosini
