;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

include-file = ~/.config/polybar/colors.ini

include-file = ~/.config/polybar/arrows

[color]

; vim:ft=dosini


[bar/kaay]
font-0 = Noto Sans Mono:size=11;2
font-1 = Noto Sans Mono Ner Font:size=11;2
font-2 = Noto Sans Mono:style=Bold:size=11;2

font-3 = 0xProto Nerd Font Mono:style=Bold:size=14;2

width = 100%
height = 23pt
radius = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 1pt

border-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = " • "
separator-foreground = ${colors.disabled}

; xwindow
modules-left = xworkspaces 
modules-center = date2
modules-right =  pulseaudio xkeyboard wired-network memory cpu

cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline = ${colors.primary}
label-active-padding = 2
label-active-margin = 1

label-occupied = %name%
label-occupied-padding = 2
label-occupied-margin = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 2


[module/xwindow]
type = internal/xwindow
label = 󱂬  %title:0:50:...%
label-empty = " "


[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
label-layout = %layout%
label-layout-font = 1
format-prefix = "  "
format-prefix-font = 3
format-prefix-foreground = ${colors.primary}
label-indicator-padding = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}


[module/memory]
type = internal/memory
interval = 5
format-prefix = "󰍛 "
format-prefix-font = 2
format-prefix-foreground = ${colors.primary}
label = %percentage_used%%
label-padding = 1


[module/cpu]
type = internal/cpu
interval = 5
format-prefix = " "
format-prefix-font = 2
format-prefix-foreground = ${colors.primary}
label = %percentage:0%%
label-padding = 1


[module/date2]
type = internal/date
interval = 5

date = "%d/%m  •  %a  •  %H:%M"

label = %date%


[module/date]
type = internal/date
interval = 5

date = "%d/%m"

format-prefix = "   "
format-prefix-font = 3
format-prefix-foreground = ${colors.primary}

label = %date%

[module/pulseaudio]
type = internal/pulseaudio

; Sink to be used, if it exists (find using `pacmd list-sinks`, name field)
; If not, uses default sink
; sink = alsa_output.pci-0000_12_00.3.analog-stereo

; Use PA_VOLUME_UI_MAX (~153%) if true, or PA_VOLUME_NORM (100%) if false
; Default: true
use-ui-max = true

; Interval for volume increase/decrease (in percent points)
; Default: 5
interval = 5

format-prefix = " "
format-prefix-font = 3
format-prefix-foreground = ${colors.primary}

; Reverses the increment/decrement on scroll event. Set this to true if you are
; using natural scrolling option on your touchpad.
; New in version 3.7.0
; Default: false
reverse-scroll = false

[module/network]
type = internal/network
interface = eth0
interface-type = wired
interval = 5.0

format-connected = <label-connected>
format-disconnected = <label-disconnected>

label-connected = %local_ip%

label-disconnected = not connected
label-disconnected-foreground = ${colors.disabled}

; @deprecated: Define min width using token specifiers (%downspeed:min% and %upspeed:min%)
; Minimum output width of upload/download rate
; Default: 3
udspeed-minwidth = 5

; Accumulate values from all interfaces
; when querying for up/downspeed rate
; Default: false
accumulate-stats = true

; Consider an `UNKNOWN` interface state as up.
; Some devices like USB network adapters have 
; an unknown state, even when they're running
; Default: false
unknown-as-up = true

; The unit used for displaying network speeds
; For example if set to the empty string, a speed of 5 KB/s is displayed as 5 K
; Default: B/s
; New in version 3.6.0
speed-unit = ''

[module/cmus]
type = custom/script
exec = ~/.local/bin/cmus-info
interval = 3
click-left = cmus-remote -u
click-middle = cmus-remote -n
click-right = cmus-remote -r

[settings]
screenchange-reload = true
pseudo-transparency = true
throttle-output = 5
throttle-output-for = 5

; vim:ft=dosini